import keyMirror from 'spacenet-redux/utils/key_mirror';

export default keyMirror({
  STREAM_REQUEST: null,
  STREAM_SUCCESS: null,
  STREAM_FAILURE: null,

  STREAMS_REQUEST: null,
  STREAMS_SUCCESS: null,
  STREAMS_FAILURE: null,

  CREATE_STREAM_REQUEST: null,
  CREATE_STREAM_SUCCESS: null,
  CREATE_STREAM_FAILURE: null,

  UPDATE_STREAM_REQUEST: null,
  UPDATE_STREAM_SUCCESS: null,
  UPDATE_STREAM_FAILURE: null,

  DELETE_STREAM_SUCCESS: null,

  GET_STREAMS_REQUEST: null,
  GET_STREAMS_SUCCESS: null,
  GET_STREAMS_FAILURE: null,

  GET_MY_STREAMS_REQUEST: null,
  GET_MY_STREAMS_SUCCESS: null,
  GET_MY_STREAMS_FAILURE: null,

  ADD_MEMBER_TO_STREAM_REQUEST: null,
  ADD_MEMBER_TO_STREAM_SUCCESS: null,
  ADD_MEMBER_TO_STREAM_FAILURE: null,

  REMOVE_MEMBER_FROM_STREAM: null,
  RECEIVED_STREAM: null,
  RECEIVED_STREAMS: null,
  RECEIVED_ALL_STREAMS: null,
  RECEIVED_STREAMS_LIST: null,
  RECEIVED_MY_STREAM_MEMBERS: null,
  RECEIVED_MY_STREAM_MEMBER: null,
  RECEIVED_STREAM_MEMBERS: null,
  RECEIVED_STREAM_MEMBER: null,
  RECEIVED_STREAM_STATS: null,
  RECEIVED_STREAM_PROPS: null,
  RECEIVED_STREAM_DELETED: null,
  RECEIVED_STREAM_UNARCHIVED: null,
  RECEIVED_LAST_VIEWED_AT: null,
  UPDATE_STREAM_HEADER: null,
  UPDATE_STREAM_PURPOSE: null,
  STREAM_MEMBER_ADDED: null,
  STREAM_MEMBER_REMOVED: null,
})