const errors = {
  ERROR_USERNAME_TAKEN: 101,
  ERROR_EMAIL_EXISTS: 102,
  ERROR_USERNAME_INVALID: 103,
  ERROR_PASSWORD_LENGTH: 104,
  ERROR_INVALID_LOGIN_CRED: 105,
  ERROR_INVALID_EXPIRED_SESSION:106,
  ERROR_RECORD_NOT_FOUND: 41,
  ERROR_INVALID_URL_PARAM: 251,
  ERROR_PG_UNIQUE: "23505",
  ERROR_CONSTRAINT_USERNAME: "users_username_key",
  ERROR_CONSTRAINT_EMAIL: "users_email_key",
};

export default errors;